// <auto-generated />
using System;
using HRMS.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMS.Migrations
{
    [DbContext(typeof(HRMSContext))]
    [Migration("20220623103322_EmployeeMaster")]
    partial class EmployeeMaster
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HRMS.Database.tblDepartment", b =>
                {
                    b.Property<uint>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("DeptId");

                    b.ToTable("tblDepartment");
                });

            modelBuilder.Entity("HRMS.Database.tblDepartWorkingRole", b =>
                {
                    b.Property<uint>("WorkingRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("DeptId")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<uint>("OrgId")
                        .HasColumnType("int unsigned");

                    b.HasKey("WorkingRoleId");

                    b.HasIndex("DeptId");

                    b.ToTable("tblDepartWorkingRole");
                });

            modelBuilder.Entity("HRMS.Database.tblDesignation", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("Level")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<uint>("OrgId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("tblDesignation");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpAddress", b =>
                {
                    b.Property<uint>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("CountryId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<uint>("StateId")
                        .HasColumnType("int unsigned");

                    b.HasKey("AddressId");

                    b.HasIndex("EmpId");

                    b.ToTable("tblEmpAddress");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpAddress_Log", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<uint?>("AddressId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ApprovalBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ApprovalDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("CountryId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpLogId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RequestedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<uint>("StateId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmpLogId");

                    b.ToTable("tblEmpAddress_Log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpBankDetails", b =>
                {
                    b.Property<uint>("BankDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<uint?>("BankId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<uint?>("DocumentId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NameonBank")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UPI")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("BankDetailId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("EmpId");

                    b.ToTable("tblEmpBankDetails");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpBankDetails_log", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<uint?>("ApprovalBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ApprovalDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint?>("BankDetailId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("BankId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<uint?>("DocumentId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("DocumentLogId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpLogId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameonBank")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RequestedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UPI")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<uint>("tblEmpDocument_logId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("BankDetailId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmpLogId");

                    b.HasIndex("tblEmpDocument_logId");

                    b.ToTable("tblEmpBankDetails_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpContacts", b =>
                {
                    b.Property<uint>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("ContactId");

                    b.HasIndex("EmpId");

                    b.ToTable("tblEmpContacts");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpContacts_Log", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ApprovalBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ApprovalDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint?>("ContactId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpLogId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RequestedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmpLogId");

                    b.ToTable("tblEmpContacts_Log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpDepartment", b =>
                {
                    b.Property<uint>("EmpDepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("DepId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("DepWorkingRoleId")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("EffectiveDt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("EmpDepId");

                    b.HasIndex("DepId");

                    b.HasIndex("DepWorkingRoleId");

                    b.HasIndex("EmpId");

                    b.ToTable("tblEmpDepartment");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpDepartment_log", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ApprovalBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ApprovalDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint?>("DepId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("DepWorkingRoleId")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("EffectiveDt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("EmpDepId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpLogId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RequestedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepId");

                    b.HasIndex("DepWorkingRoleId");

                    b.HasIndex("EmpDepId");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmpLogId");

                    b.ToTable("tblEmpDepartment_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpDesignation", b =>
                {
                    b.Property<uint>("EmpDesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("DesId")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("EffectiveDt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("GradeId")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("EmpDesId");

                    b.HasIndex("DesId");

                    b.HasIndex("EmpId");

                    b.HasIndex("GradeId");

                    b.ToTable("tblEmpDesignation");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpDesignation_log", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ApprovalBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ApprovalDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint?>("DesId")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("EffectiveDt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("EmpDesId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpLogId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint?>("GradeId")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RequestedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DesId");

                    b.HasIndex("EmpDesId");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmpLogId");

                    b.HasIndex("GradeId");

                    b.ToTable("tblEmpDesignation_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpDocument", b =>
                {
                    b.Property<uint>("DocumentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("DocumentPaths")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("DocumentDetailId");

                    b.HasIndex("EmpId");

                    b.ToTable("tblEmpDocument");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpDocument_log", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ApprovalBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ApprovalDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<uint?>("DocumentDetailId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("DocumentPaths")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpLogId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RequestedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentDetailId");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmpLogId");

                    b.ToTable("tblEmpDocument_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpFamilyDetails", b =>
                {
                    b.Property<uint>("FamilyDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("IDProofNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("IDProofType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDependent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsNominee")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<double>("NomineePercentage")
                        .HasColumnType("double");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RelationName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("enmFamily")
                        .HasColumnType("int");

                    b.HasKey("FamilyDetailId");

                    b.HasIndex("EmpId");

                    b.ToTable("tblEmpFamilyDetails");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpFamilyDetails_log", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ApprovalBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ApprovalDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpLogId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint?>("FamilyDetailId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("IDProofNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("IDProofType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDependent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsNominee")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<double>("NomineePercentage")
                        .HasColumnType("double");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RelationName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RequestedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("enmFamily")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmpLogId");

                    b.HasIndex("FamilyDetailId");

                    b.ToTable("tblEmpFamilyDetails_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpLocation", b =>
                {
                    b.Property<uint>("EmpLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("CompanyId")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("EffectiveDt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("LocationId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<uint?>("SubLocationId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ZoneId")
                        .HasColumnType("int unsigned");

                    b.HasKey("EmpLocationId");

                    b.HasIndex("EmpId");

                    b.ToTable("tblEmpLocation");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpLocation_log", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ApprovalBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ApprovalDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint?>("CompanyId")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("EffectiveDt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpLocationId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpLogId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("LocationId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RequestedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<uint?>("SubLocationId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ZoneId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmpLocationId");

                    b.HasIndex("EmpLogId");

                    b.ToTable("tblEmpLocation_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmployeeMaster", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Title")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tblEmployeeMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblEmployeeMaster_log", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ApprovalBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ApprovalDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RequestedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Title")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.ToTable("tblEmployeeMaster_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpManager", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("EffectiveDt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("ManagerId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.HasIndex("ManagerId");

                    b.ToTable("tblEmpManager");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpManager_log", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ApprovalBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ApprovalDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("EffectiveDt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpLogId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("ManagerId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RequestedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmpLogId");

                    b.HasIndex("ManagerId");

                    b.ToTable("tblEmpManager_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpOfficialDetails", b =>
                {
                    b.Property<uint>("OfficialDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ActualNoticePeriodDay")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ActualNoticePeriodMonth")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ActualProbationPeriodDay")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ActualProbationPeriodMonth")
                        .HasColumnType("int unsigned");

                    b.Property<string>("AdharNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("ComJoiningDt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("DefaultNoticePeriodDay")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("DefaultNoticePeriodMonth")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("DefaultProbationPeriodDay")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("DefaultProbationPeriodMonth")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("JoiningRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("OrgJoiningDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PanName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PanNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("TerminationDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TerminationRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("hr_spoc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("OfficialDetailId");

                    b.HasIndex("EmpId");

                    b.ToTable("tblEmpOfficialDetails");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpOfficialDetails_log", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ActualNoticePeriodDay")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ActualNoticePeriodMonth")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ActualProbationPeriodDay")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ActualProbationPeriodMonth")
                        .HasColumnType("int unsigned");

                    b.Property<string>("AdharNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<uint?>("ApprovalBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ApprovalDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("ComJoiningDt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("DefaultNoticePeriodDay")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("DefaultNoticePeriodMonth")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("DefaultProbationPeriodDay")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("DefaultProbationPeriodMonth")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpLogId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("JoiningRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<uint?>("OfficialDetailId")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("OrgJoiningDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PanName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PanNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RequestedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("TerminationDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TerminationRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("hr_spoc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmpLogId");

                    b.HasIndex("OfficialDetailId");

                    b.ToTable("tblEmpOfficialDetails_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpPersonalDetails", b =>
                {
                    b.Property<uint>("PersonalDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("AnniversaryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Religion")
                        .HasColumnType("int");

                    b.HasKey("PersonalDetailId");

                    b.HasIndex("EmpId");

                    b.ToTable("tblEmpPersonalDetails");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpPersonalDetails_log", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("AnniversaryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("ApprovalBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ApprovalDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpLogId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<uint?>("PersonalDetailId")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Religion")
                        .HasColumnType("int");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RequestedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmpLogId");

                    b.HasIndex("PersonalDetailId");

                    b.ToTable("tblEmpPersonalDetails_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpQualification", b =>
                {
                    b.Property<uint>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<byte>("CourseType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("DurationEndMonth")
                        .HasColumnType("tinyint unsigned");

                    b.Property<ushort>("DurationEndYear")
                        .HasColumnType("smallint unsigned");

                    b.Property<byte>("DurationStartMonth")
                        .HasColumnType("tinyint unsigned");

                    b.Property<ushort>("DurationStartYear")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<double>("Percentage")
                        .HasColumnType("double");

                    b.Property<int>("QualificationType")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("QualificationId");

                    b.HasIndex("EmpId");

                    b.ToTable("tblEmpQualification");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpQualification_log", b =>
                {
                    b.Property<uint>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ApprovalBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ApprovalDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<byte>("CourseType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("DurationEndMonth")
                        .HasColumnType("tinyint unsigned");

                    b.Property<short>("DurationEndYear")
                        .HasColumnType("smallint");

                    b.Property<byte>("DurationStartMonth")
                        .HasColumnType("tinyint unsigned");

                    b.Property<short>("DurationStartYear")
                        .HasColumnType("smallint");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpLogId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<double>("Percentage")
                        .HasColumnType("double");

                    b.Property<int>("QualificationType")
                        .HasColumnType("int");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RequestedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("QualificationId");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmpLogId");

                    b.ToTable("tblEmpQualification_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpWorkExperience", b =>
                {
                    b.Property<uint>("WorkExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<double>("AnnualSalary")
                        .HasColumnType("double");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("WorkExperienceId");

                    b.HasIndex("EmpId");

                    b.ToTable("tblEmpWorkExperience");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpWorkExperience_log", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<double>("AnnualSalary")
                        .HasColumnType("double");

                    b.Property<uint?>("ApprovalBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ApprovalDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<uint?>("EmpId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("EmpLogId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<uint>("RequestedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RequestedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("WorkExperienceId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmpLogId");

                    b.HasIndex("WorkExperienceId");

                    b.ToTable("tblEmpWorkExperience_log");
                });

            modelBuilder.Entity("HRMS.Database.tblGrade", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("Level")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<uint>("OrgId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("tblGrade");
                });

            modelBuilder.Entity("HRMS.Database.tblHolidayMaster", b =>
                {
                    b.Property<uint>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HolidayName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("Todate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("HolidayId");

                    b.ToTable("tblHolidayMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblReligionMaster", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("Level")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("ModifiedBy")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedRemarks")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<uint>("OrgId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("tblReligionMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblDepartWorkingRole", b =>
                {
                    b.HasOne("HRMS.Database.tblDepartment", "tblDepartment")
                        .WithMany()
                        .HasForeignKey("DeptId");

                    b.Navigation("tblDepartment");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpAddress", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.Navigation("tblEmployeeMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpAddress_Log", b =>
                {
                    b.HasOne("HRMS.Database.tblEmpAddress", "tblEmpAddress")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster_log", "tblEmployeeMaster_log")
                        .WithMany()
                        .HasForeignKey("EmpLogId");

                    b.Navigation("tblEmpAddress");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblEmployeeMaster_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpBankDetails", b =>
                {
                    b.HasOne("HRMS.Database.tblEmpDocument", "tblEmpDocument")
                        .WithMany()
                        .HasForeignKey("DocumentId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.Navigation("tblEmpDocument");

                    b.Navigation("tblEmployeeMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpBankDetails_log", b =>
                {
                    b.HasOne("HRMS.Database.tblEmpBankDetails", "tblEmpBankDetails")
                        .WithMany()
                        .HasForeignKey("BankDetailId");

                    b.HasOne("HRMS.Database.tblEmpDocument", "tblEmpDocument")
                        .WithMany()
                        .HasForeignKey("DocumentId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster_log", "tblEmployeeMaster_log")
                        .WithMany()
                        .HasForeignKey("EmpLogId");

                    b.HasOne("HRMS.Database.tblEmpDocument_log", "tblEmpDocument_log")
                        .WithMany()
                        .HasForeignKey("tblEmpDocument_logId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblEmpBankDetails");

                    b.Navigation("tblEmpDocument");

                    b.Navigation("tblEmpDocument_log");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblEmployeeMaster_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpContacts", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.Navigation("tblEmployeeMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpContacts_Log", b =>
                {
                    b.HasOne("HRMS.Database.tblEmpContacts", "tblEmpContacts")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster_log", "tblEmployeeMaster_log")
                        .WithMany()
                        .HasForeignKey("EmpLogId");

                    b.Navigation("tblEmpContacts");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblEmployeeMaster_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpDepartment", b =>
                {
                    b.HasOne("HRMS.Database.tblDepartment", "tblDepartment")
                        .WithMany()
                        .HasForeignKey("DepId");

                    b.HasOne("HRMS.Database.tblDepartWorkingRole", "tblDepartWorkingRole")
                        .WithMany()
                        .HasForeignKey("DepWorkingRoleId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.Navigation("tblDepartWorkingRole");

                    b.Navigation("tblDepartment");

                    b.Navigation("tblEmployeeMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpDepartment_log", b =>
                {
                    b.HasOne("HRMS.Database.tblDepartment", "tblDepartment")
                        .WithMany()
                        .HasForeignKey("DepId");

                    b.HasOne("HRMS.Database.tblDepartWorkingRole", "tblDepartWorkingRole")
                        .WithMany()
                        .HasForeignKey("DepWorkingRoleId");

                    b.HasOne("HRMS.Database.tblEmpDepartment", "tblEmpDepartment")
                        .WithMany()
                        .HasForeignKey("EmpDepId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster_log", "tblEmployeeMaster_log")
                        .WithMany()
                        .HasForeignKey("EmpLogId");

                    b.Navigation("tblDepartWorkingRole");

                    b.Navigation("tblDepartment");

                    b.Navigation("tblEmpDepartment");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblEmployeeMaster_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpDesignation", b =>
                {
                    b.HasOne("HRMS.Database.tblDesignation", "tblDesignation")
                        .WithMany()
                        .HasForeignKey("DesId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblGrade", "tblGrade")
                        .WithMany()
                        .HasForeignKey("GradeId");

                    b.Navigation("tblDesignation");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblGrade");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpDesignation_log", b =>
                {
                    b.HasOne("HRMS.Database.tblDesignation", "tblDesignation")
                        .WithMany()
                        .HasForeignKey("DesId");

                    b.HasOne("HRMS.Database.tblEmpDesignation", "tblEmpDesignation")
                        .WithMany()
                        .HasForeignKey("EmpDesId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster_log", "tblEmployeeMaster_log")
                        .WithMany()
                        .HasForeignKey("EmpLogId");

                    b.HasOne("HRMS.Database.tblGrade", "tblGrade")
                        .WithMany()
                        .HasForeignKey("GradeId");

                    b.Navigation("tblDesignation");

                    b.Navigation("tblEmpDesignation");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblEmployeeMaster_log");

                    b.Navigation("tblGrade");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpDocument", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.Navigation("tblEmployeeMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpDocument_log", b =>
                {
                    b.HasOne("HRMS.Database.tblEmpDocument", "tblEmpDocument")
                        .WithMany()
                        .HasForeignKey("DocumentDetailId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster_log", "tblEmployeeMaster_log")
                        .WithMany()
                        .HasForeignKey("EmpLogId");

                    b.Navigation("tblEmpDocument");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblEmployeeMaster_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpFamilyDetails", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.Navigation("tblEmployeeMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpFamilyDetails_log", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster_log", "tblEmployeeMaster_log")
                        .WithMany()
                        .HasForeignKey("EmpLogId");

                    b.HasOne("HRMS.Database.tblEmpFamilyDetails", "tblEmpFamilyDetails")
                        .WithMany()
                        .HasForeignKey("FamilyDetailId");

                    b.Navigation("tblEmpFamilyDetails");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblEmployeeMaster_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpLocation", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.Navigation("tblEmployeeMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpLocation_log", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblEmpLocation", "tblEmpLocation")
                        .WithMany()
                        .HasForeignKey("EmpLocationId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster_log", "tblEmployeeMaster_log")
                        .WithMany()
                        .HasForeignKey("EmpLogId");

                    b.Navigation("tblEmpLocation");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblEmployeeMaster_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmployeeMaster_log", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.Navigation("tblEmployeeMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpManager", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster_Mgr")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblEmployeeMaster_Mgr");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpManager_log", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster_log", "tblEmployeeMaster_log")
                        .WithMany()
                        .HasForeignKey("EmpLogId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster_Mgr")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblEmployeeMaster_Mgr");

                    b.Navigation("tblEmployeeMaster_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpOfficialDetails", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.Navigation("tblEmployeeMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpOfficialDetails_log", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster_log", "tblEmployeeMaster_log")
                        .WithMany()
                        .HasForeignKey("EmpLogId");

                    b.HasOne("HRMS.Database.tblEmpOfficialDetails", "tblEmpOfficialDetails")
                        .WithMany()
                        .HasForeignKey("OfficialDetailId");

                    b.Navigation("tblEmpOfficialDetails");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblEmployeeMaster_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpPersonalDetails", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.Navigation("tblEmployeeMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpPersonalDetails_log", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster_log", "tblEmployeeMaster_log")
                        .WithMany()
                        .HasForeignKey("EmpLogId");

                    b.HasOne("HRMS.Database.tblEmpPersonalDetails", "tblEmpPersonalDetails")
                        .WithMany()
                        .HasForeignKey("PersonalDetailId");

                    b.Navigation("tblEmpPersonalDetails");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblEmployeeMaster_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpQualification", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.Navigation("tblEmployeeMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpQualification_log", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster_log", "tblEmployeeMaster_log")
                        .WithMany()
                        .HasForeignKey("EmpLogId");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblEmployeeMaster_log");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpWorkExperience", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.Navigation("tblEmployeeMaster");
                });

            modelBuilder.Entity("HRMS.Database.tblEmpWorkExperience_log", b =>
                {
                    b.HasOne("HRMS.Database.tblEmployeeMaster", "tblEmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.HasOne("HRMS.Database.tblEmployeeMaster_log", "tblEmployeeMaster_log")
                        .WithMany()
                        .HasForeignKey("EmpLogId");

                    b.HasOne("HRMS.Database.tblEmpWorkExperience", "tblEmpWorkExperience")
                        .WithMany()
                        .HasForeignKey("WorkExperienceId");

                    b.Navigation("tblEmpWorkExperience");

                    b.Navigation("tblEmployeeMaster");

                    b.Navigation("tblEmployeeMaster_log");
                });
#pragma warning restore 612, 618
        }
    }
}
